Repository Sweepic/sweepic-Server, pull requests merged in 2025-02, with the labels that each got.

#132 feat: 태그 생성 API (수정도 일괄 생성으로)
  .gitignore
  .idea/.gitignore
  .idea/dataSources.xml
  .idea/modules.xml
  .idea/sweepic-Server.iml
  .idea/vcs.xml
  package.json
  src/app.ts
  src/controllers/memo-image.controller.ts
  src/controllers/tag.controller.ts
  src/controllers/trust.controller.ts
  src/dtos/image.dto.ts
  src/dtos/tag.dto.ts
  src/errors.ts
  src/models/image.model.ts
  src/models/tag.model.ts
  src/repositories/tag.repositories.ts
  src/repositories/trust.repositories.ts
  src/routers/tag.router.ts
  src/routers/trust.router.ts
  src/services/tag.service.ts
  src/services/trust.service.ts
  src/utils/tag.utils.ts
  tsconfig.json
Labels: :sparkles: FEAT

#133 refactor: lint 규칙 강화 및 수정
  @types/environment.d.ts
  @types/express.d.ts
  eslint.config.js
  package.json
  src/app.ts
  src/auth.config.ts
  src/controllers/challenge.controllers.ts
  src/controllers/challenge.location.controllers.ts
  src/controllers/challenge.weekly.controllers.ts
  src/controllers/memo-createFolderOCR.Controller.ts
  src/controllers/memo-folder.controller.ts
  src/controllers/memo-image.controller.ts
  src/controllers/memo-updateFolderOCR.Controller.ts
  src/controllers/tag.controller.ts
  src/controllers/tags-ai.controller.ts
  src/controllers/trust.controller.ts
  src/controllers/tsoaTag.controller.ts
  src/db.config.ts
  src/dtos/tag.dto.ts
  src/repositories/challenge.repositories.ts
  src/repositories/memo-OCR.repositoy.ts
  src/repositories/memo-folder.repository.ts
  src/repositories/memo-image.repository.ts
  src/repositories/tag.repositories.ts
  src/repositories/trust.repositories.ts
  src/repositories/tsoaTag.repository.ts
  src/repositories/weekly.repositories.ts
  src/routers/auth.routers.ts
  src/s3/awsS3Client.ts
  src/s3/get-presigned-url.ts
  src/s3/image.deleter.ts
  src/s3/image.mover.ts
  src/s3/image.uploader.ts
  src/services/challenge.location.services.ts
  src/services/challenge.services.ts
  src/services/challenge.weekly.services.ts
  src/services/memo-folder.service.ts
  src/services/memo-image.service.ts
  src/services/memo-ocrService.ts
  src/services/tag.service.ts
  src/services/tags-ai.service.ts
  src/services/tsoaImage.service.ts
  src/services/tsoaTag.service.ts
  tsconfig.json
  yarn.lock
Labels: :recycle: REFACTOR

#139 refactor: 비교 연산자 수정, 안 쓰는 라이브러리 삭제, console 삭제, 템플릿 리터럴 사용
  src/controllers/memo-folder.controller.ts
  src/controllers/memo-image.controller.ts
  src/repositories/memo-folder.repository.ts
  src/repositories/memo-image.repository.ts
  src/s3/image.mover.ts
  src/s3/image.uploader.ts
  src/services/memo-folder.service.ts
  src/services/memo-image.service.ts
Labels: :recycle: REFACTOR, :bug: FIX

#130 [SWEP-74] 메모장 텍스트 수정 API 에러 처리 추가 및 swagger 실패 응답 예시 작성 (#129)
  src/app.ts
  src/controllers/memo-folder.controller.ts
  src/controllers/memo-image.controller.ts
  src/errors.ts
  src/repositories/memo-folder.repository.ts
  src/repositories/memo-image.repository.ts
  src/s3/image.mover.ts
  src/s3/image.uploader.ts
  src/services/memo-folder.service.ts
  src/services/memo-image.service.ts
  swagger/openapi.json
Labels: :recycle: REFACTOR

#136 [SWEP-53] 태그 생성 API 및 린트 설정
  .gitignore
  .idea/.gitignore
  .idea/dataSources.xml
  .idea/modules.xml
  .idea/sweepic-Server.iml
  .idea/vcs.xml
  @types/environment.d.ts
  @types/express.d.ts
  eslint.config.js
  package.json
  src/app.ts
  src/auth.config.ts
  src/controllers/challenge.controllers.ts
  src/controllers/challenge.location.controllers.ts
  src/controllers/challenge.weekly.controllers.ts
  src/controllers/memo-createFolderOCR.Controller.ts
  src/controllers/memo-image.controller.ts
  src/controllers/memo-updateFolderOCR.Controller.ts
  src/controllers/tag.controller.ts
  src/controllers/tags-ai.controller.ts
  src/controllers/trust.controller.ts
  src/controllers/tsoaTag.controller.ts
  src/db.config.ts
  src/dtos/image.dto.ts
  src/dtos/tag.dto.ts
  src/errors.ts
  src/models/image.model.ts
  src/models/tag.model.ts
  src/repositories/challenge.repositories.ts
  src/repositories/memo-OCR.repositoy.ts
  src/repositories/tag.repositories.ts
  src/repositories/trust.repositories.ts
  src/repositories/tsoaTag.repository.ts
  src/repositories/weekly.repositories.ts
  src/routers/auth.routers.ts
  src/routers/tag.router.ts
  src/routers/trust.router.ts
  src/s3/awsS3Client.ts
  src/s3/get-presigned-url.ts
  src/s3/image.deleter.ts
  src/s3/image.uploader.ts
  src/services/challenge.location.services.ts
  src/services/challenge.services.ts
  src/services/challenge.weekly.services.ts
  src/services/memo-folder.service.ts
  src/services/memo-image.service.ts
  src/services/memo-ocrService.ts
  src/services/tag.service.ts
  src/services/tags-ai.service.ts
  src/services/trust.service.ts
  src/services/tsoaImage.service.ts
  src/services/tsoaTag.service.ts
  src/utils/tag.utils.ts
  tsconfig.json
  yarn.lock
Labels: :recycle: REFACTOR, :bug: FIX, :sparkles: FEAT

#144 [SWEP-79] 마이페이지 API
  src/app.ts
  src/controllers/user.mypage.controllers.ts
  src/models/user.model.ts
  src/repositories/mypage.repository.ts
  src/routers/mypage.routers.ts
  src/services/mypage.service.ts
Labels: :sparkles: FEAT

#152 fix: eslint undef 설정, 스웨거에서 로컬서버와 배포서버를 선택할수 있게 만듦
  @types/express.d.ts
  config/tsoa.json
  eslint.config.js
  src/app.ts
  src/controllers/user.mypage.controllers.ts
  src/models/user.model.ts
  src/repositories/mypage.repository.ts
  src/routers/mypage.routers.ts
  src/services/mypage.service.ts
  swagger/openapi.json
  swagger/swagger.json
  swagger/swagger.ts
Labels: :recycle: REFACTOR, :bug: FIX

#149 [SWEP-55] 네이버 API
  package.json
  src/controllers/challenge.controllers.ts
  src/errors.ts
  src/models/challenge.entities.ts
  src/routers/challenge.router.ts
  src/services/challenge.location.services.ts
  src/utils/challenge.utils.ts
  yarn.lock
Labels: :sparkles: FEAT

#162 Refactor: tsoaResponse에서 success 형태 변경
  package.json
  src/controllers/challenge.controllers.ts
  src/errors.ts
  src/models/challenge.entities.ts
  src/models/tsoaResponse.ts
  src/routers/challenge.router.ts
  src/services/challenge.location.services.ts
  src/utils/challenge.utils.ts
  yarn.lock
Labels: :recycle: REFACTOR

#151 [SWEP-80] 태그 조회, 이미지 조회 API 응답에러 추가, tsoa 응답 통일 인터페이스 구현, lint 업데이트
  .github/workflows/deploy-main.yml
  @types/environment.d.ts
  @types/express.d.ts
  config/tsoa.json
  eslint.config.js
  package.json
  src/app.ts
  src/controllers/tsoaImage.controller.ts
  src/controllers/tsoaTag.controller.ts
  src/dtos/tsoaImage.dto.ts
  src/dtos/tsoaTag.dto.ts
  src/errors.ts
  src/models/tsoaResponse.ts
  src/repositories/tsoaImage.repository.ts
  src/repositories/tsoaTag.repository.ts
  src/routers/tsoaRoutes.ts
  src/services/memo-folder.service.ts
  src/services/memo-image.service.ts
  swagger/openapi.json
  swagger/swagger.json
  swagger/swagger.ts
  tsconfig.json
  yarn.lock
Labels: :recycle: REFACTOR, :bug: FIX

#165 feature: 특정이미지의 태그 조회 API 구현
  src/controllers/tsoaImage.controller.ts
  src/controllers/tsoaTag.controller.ts
  src/dtos/tsoaTag.dto.ts
  src/models/tsoaTag.model.ts
  src/repositories/tsoaImage.repository.ts
  src/repositories/tsoaTag.repository.ts
  src/routers/tsoaRoutes.ts
  src/services/tsoaTag.service.ts
  swagger/swagger.json
Labels: :sparkles: FEAT

#171 fix: 검색어가 빈 문자열이거나 공백만 입력될 경우 에러 처리
  src/controllers/tsoa.memo-folder.controller.ts
Labels: :bug: FIX

#155 [SWEP-83] 사용자 로그아웃 구현
  src/controllers/user.mypage.controllers.ts
  src/repositories/mypage.repository.ts
  src/routers/mypage.routers.ts
  src/services/mypage.service.ts
Labels: :sparkles: FEAT

#166 [SWEP-70] 이미지의 태그조회 API
  src/controllers/tsoaImage.controller.ts
  src/controllers/tsoaTag.controller.ts
  src/dtos/tsoaTag.dto.ts
  src/models/tsoaTag.model.ts
  src/repositories/tsoaImage.repository.ts
  src/repositories/tsoaTag.repository.ts
  src/routers/tsoaRoutes.ts
  src/services/tsoaTag.service.ts
  swagger/swagger.json
Labels: :sparkles: FEAT

#180 [SWEP-71] 이미지 데이터 생성 API 구현
  src/ai/ai-upload.ts
  src/controllers/memo-createFolderOCR.Controller.ts
  src/controllers/memo-updateFolderOCR.Controller.ts
  src/controllers/tsoaImage.controller.ts
  src/controllers/tsoaTag.controller.ts
  src/controllers/user.mypage.controllers.ts
  src/dtos/tsoaImage.dto.ts
  src/dtos/tsoaTag.dto.ts
  src/models/memo-OCR.model.ts
  src/models/tsoaImage.model.ts
  src/models/tsoaTag.model.ts
  src/repositories/memo-OCR.repositoy.ts
  src/repositories/mypage.repository.ts
  src/repositories/tsoaImage.repository.ts
  src/repositories/tsoaTag.repository.ts
  src/routers/memo.router.ts
  src/routers/mypage.routers.ts
  src/routers/tsoaRoutes.ts
  src/services/memo-ocrService.ts
  src/services/mypage.service.ts
  src/services/tsoaImage.service.ts
  src/services/tsoaTag.service.ts
  swagger/swagger.json
Labels: :sparkles: FEAT

#177 [SWEP-86] 히스토리 API
  src/controllers/history.controller.ts
  src/dtos/history.dto.ts
  src/errors.ts
  src/models/history.model.ts
  src/repositories/history.repositories.ts
  src/routers/tsoaRoutes.ts
  src/services/history.services.ts
  swagger/swagger.json
Labels: :sparkles: FEAT

#161 [SWEP-58] 휴지통 API 구현
  src/app.ts
  src/controllers/trust.controller.ts
  src/repositories/trust.repositories.ts
  src/routers/mypage.routers.ts
  src/routers/trust.router.ts
  src/services/trust.service.ts
  src/utils/tag.utils.ts
Labels: :sparkles: FEAT

#189 refactor: 메모 텍스트 저장 API tsoa 적용 및 여러 multer 객체 사용할 수 있도록 구현
  config/tsoa.json
  src/app.ts
  src/controllers/memo-createFolderOCR.Controller.ts
  src/controllers/memo-folder.controller.ts
  src/controllers/memo-image.controller.ts
  src/controllers/memo-updateFolderOCR.Controller.ts
  src/controllers/trust.controller.ts
  src/controllers/tsoa.memo-folder.controller.ts
  src/controllers/tsoa.memo-image.controller.ts
  src/dtos/memo-folder.dto.ts
  src/dtos/memo-image.dto.ts
  src/models/memo-folder.model.ts
  src/models/memo-image.model.ts
  src/repositories/memo-folder.repository.ts
  src/repositories/memo-image.repository.ts
  src/routers/memo.router.ts
  src/routers/tsoaRoutes.ts
  src/s3/image.mover.ts
  src/s3/image.uploader.ts
  src/services/memo-folder.service.ts
  src/services/memo-image.service.ts
  swagger/openapi.json
  swagger/swagger.json
Labels: :recycle: REFACTOR, :bug: FIX

#191 [SWEP-89] 메모 텍스트 저장 API tsoa 적용 및 여러 multer 객체 사용할 수 있도록 구현 (#189)
  config/tsoa.json
  src/app.ts
  src/controllers/memo-createFolderOCR.Controller.ts
  src/controllers/memo-folder.controller.ts
  src/controllers/memo-image.controller.ts
  src/controllers/memo-updateFolderOCR.Controller.ts
  src/controllers/tsoa.memo-folder.controller.ts
  src/controllers/tsoa.memo-image.controller.ts
  src/dtos/memo-folder.dto.ts
  src/dtos/memo-image.dto.ts
  src/models/memo-folder.model.ts
  src/models/memo-image.model.ts
  src/repositories/memo-folder.repository.ts
  src/repositories/memo-image.repository.ts
  src/routers/memo.router.ts
  src/routers/tsoaRoutes.ts
  src/s3/image.mover.ts
  src/s3/image.uploader.ts
  src/services/memo-folder.service.ts
  src/services/memo-image.service.ts
  swagger/openapi.json
  swagger/swagger.json
Labels: :recycle: REFACTOR, :bug: FIX

#194 fix: 메모장 사진/텍스트 저장 관련 API 에러 처리 및 @Middlewares() 적용
  src/ai/ai-upload.middleware.ts
  src/app.ts
  src/controllers/memo-createFolderOCR.Controller.ts
  src/controllers/memo-updateFolderOCR.Controller.ts
  src/controllers/trust.controller.ts
  src/controllers/tsoa.memo-folder.controller.ts
  src/controllers/tsoa.memo-image.controller.ts
  src/s3/image.uploader.middleware.ts
  swagger/openapi.json
Labels: :bug: FIX

#195 [SWEP-91] 메모장 사진/텍스트 저장 관련 API 에러 처리 및 @Middlewares() (#194)
  src/ai/ai-upload.middleware.ts
  src/app.ts
  src/controllers/memo-createFolderOCR.Controller.ts
  src/controllers/memo-updateFolderOCR.Controller.ts
  src/controllers/trust.controller.ts
  src/controllers/tsoa.memo-folder.controller.ts
  src/controllers/tsoa.memo-image.controller.ts
  src/s3/image.uploader.middleware.ts
  swagger/openapi.json
Labels: :bug: FIX

#198 [SWEP-94] 태그 라벨링 AI 멀티파트 구현 (#197)
  src/app.ts
  src/controllers/tags-ai.controller.ts
  src/routers/tsoaRoutes.ts
  swagger/openapi.json
Labels: :recycle: REFACTOR, :bug: FIX

#200 fix: 메모장 사진 업로드 및 저장 로직 개선
  src/s3/image.uploader.ts
Labels: :recycle: REFACTOR, :bug: FIX

#202 fix: 폴더 생성 및 사진 저장 API 주석처리 + multer 미들웨어 실행 전에 폴더 ID 검사
  src/controllers/tsoa.memo-folder.controller.ts
  src/routers/tsoaRoutes.ts
  src/s3/image.uploader.middleware.ts
  src/s3/image.uploader.ts
  swagger/swagger.json
Labels: :recycle: REFACTOR, :bug: FIX

#201 [SWEP-96] 메모장 사진 업로드 및 저장 로직 개선 (#200)
  config/tsoa.json
  src/controllers/tsoa.memo-folder.controller.ts
  src/routers/tsoaRoutes.ts
  src/s3/image.uploader.middleware.ts
  src/s3/image.uploader.ts
  swagger/swagger.json
Labels: :recycle: REFACTOR, :bug: FIX

#205 [SWEP-98] 챌린지 API tsoa 변환
  src/app.ts
  src/controllers/challenge.controller.ts
  src/controllers/challenge.controllers.ts
  src/controllers/challenge.location.controller.ts
  src/controllers/challenge.location.controllers.ts
  src/controllers/challenge.weekly.controller.ts
  src/controllers/challenge.weekly.controllers.ts
  src/controllers/history.controller.ts
  src/dtos/challenge.dtos.ts
  src/models/challenge.entities.ts
  src/repositories/challenge.repositories.ts
  src/routers/challenge.router.ts
  src/routers/tsoaRoutes.ts
  src/services/challenge.location.services.ts
  src/services/challenge.services.ts
  swagger/openapi.json
  swagger/swagger.json
Labels: :recycle: REFACTOR, :bug: FIX

#207 [SWEP-58] 휴지통 api 변경사항 및 api 추가
  src/controllers/trust.controller.ts
  src/repositories/trust.repositories.ts
  src/routers/trust.router.ts
  src/services/trust.service.ts
Labels: :bug: FIX, :sparkles: FEAT

#210 refactor: 메모 폴더명 공백 입력 시 에러 처리
  src/controllers/tsoa.memo-folder.controller.ts
  src/errors.ts
  swagger/swagger.json
Labels: :recycle: REFACTOR

#213 [SWEP-101] 히스토리 API 수정
  src/controllers/history.controller.ts
  src/db.config.ts
  src/dtos/history.dto.ts
  src/models/history.model.ts
  src/repositories/history.repositories.ts
  src/routers/tsoaRoutes.ts
  src/services/history.services.ts
  swagger/swagger.json
Labels: :recycle: REFACTOR

#215 [SWEP-62] Tsoa 변환(User, Tag, Image, Trash) , 휴지통 API 수정
  config/tsoa.json
  src/ai/ai-upload.middleware.ts
  src/app.ts
  src/controllers/challenge.controller.ts
  src/controllers/challenge.location.controller.ts
  src/controllers/challenge.weekly.controller.ts
  src/controllers/memo-createFolderOCR.controller.ts
  src/controllers/memo-updateFolderOCR.controller.ts
  src/controllers/tag.controller.ts
  src/controllers/tags-ai.controller.ts
  src/controllers/trash.controller.ts
  src/controllers/trust.controller.ts
  src/controllers/tsoa.memo-folder.controller.ts
  src/controllers/tsoa.memo-image.controller.ts
  src/controllers/tsoaTag.controller.ts
  src/controllers/user.controller.ts
  src/controllers/user.mypage.controllers.ts
  src/dtos/trash.dto.ts
  src/dtos/tsoaTag.dto.ts
  src/models/tsoaTag.model.ts
  src/models/user.model.ts
  src/repositories/mypage.repository.ts
  src/repositories/tag.repositories.ts
  src/repositories/trash.repository.ts
  src/repositories/trust.repositories.ts
  src/repositories/tsoaTag.repository.ts
  src/repositories/user.repository.ts
  src/routers/mypage.routers.ts
  src/routers/tag.router.ts
  src/routers/trust.router.ts
  src/routers/tsoaRoutes.ts
  src/routers/user.router.ts
  src/services/memo-ocrService.ts
  src/services/mypage.service.ts
  src/services/tag.service.ts
  src/services/trash.service.ts
  src/services/trust.service.ts
  src/services/tsoaTag.service.ts
  src/services/user.service.ts
  swagger/swagger.json
Labels: :recycle: REFACTOR, :bug: FIX

#217 fix: resolve conflict
  src/controllers/history.controller.ts
  src/db.config.ts
  src/dtos/history.dto.ts
  src/models/history.model.ts
  src/repositories/history.repositories.ts
  src/routers/tsoaRoutes.ts
  src/services/history.services.ts
  swagger/swagger.json
Labels: :bug: FIX

#219 fix: swagger.json 생성
  swagger/swagger.json
Labels: :bug: FIX

#218 [SWEP-62] Tsoa 변환(User, Tag, Image, Trash), 휴지통 API 수정
  config/tsoa.json
  src/ai/ai-upload.middleware.ts
  src/app.ts
  src/controllers/challenge.controller.ts
  src/controllers/challenge.location.controller.ts
  src/controllers/challenge.weekly.controller.ts
  src/controllers/memo-createFolderOCR.controller.ts
  src/controllers/memo-updateFolderOCR.controller.ts
  src/controllers/tag.controller.ts
  src/controllers/tags-ai.controller.ts
  src/controllers/trash.controller.ts
  src/controllers/trust.controller.ts
  src/controllers/tsoa.memo-folder.controller.ts
  src/controllers/tsoa.memo-image.controller.ts
  src/controllers/tsoaTag.controller.ts
  src/controllers/user.controller.ts
  src/controllers/user.mypage.controllers.ts
  src/dtos/trash.dto.ts
  src/dtos/tsoaTag.dto.ts
  src/models/tsoaTag.model.ts
  src/models/user.model.ts
  src/repositories/mypage.repository.ts
  src/repositories/tag.repositories.ts
  src/repositories/trash.repository.ts
  src/repositories/trust.repositories.ts
  src/repositories/tsoaTag.repository.ts
  src/repositories/user.repository.ts
  src/routers/mypage.routers.ts
  src/routers/tag.router.ts
  src/routers/trust.router.ts
  src/routers/tsoaRoutes.ts
  src/routers/user.router.ts
  src/services/memo-ocrService.ts
  src/services/mypage.service.ts
  src/services/tag.service.ts
  src/services/trash.service.ts
  src/services/trust.service.ts
  src/services/tsoaTag.service.ts
  src/services/user.service.ts
  swagger/swagger.json
Labels: :recycle: REFACTOR, :bug: FIX, :sparkles: FEAT

#223 [SWEP-104] 카카오 로그인 콜백 주소 수정
  config/tsoa.json
  src/auth.config.ts
Labels: :recycle: REFACTOR

#224 [SWEP-104] 카카오 로그인 콜백 주소 수정
  config/tsoa.json
  src/auth.config.ts
Labels: :recycle: REFACTOR

#228 [SWEP-110] 챌린지 이미지 업로드 기능
  src/controllers/challenge.controller.ts
  src/dtos/challenge.dtos.ts
  src/errors.ts
  src/models/challenge.entities.ts
  src/repositories/challenge.repositories.ts
  src/routers/tsoaRoutes.ts
  src/services/challenge.services.ts
  swagger/swagger.json
Labels: :recycle: REFACTOR, :sparkles: FEAT

#229 fix: 회원가입이후 유저 상태 수정
  src/routers/auth.routers.ts
  src/services/user.service.ts
Labels: :bug: FIX

#230 fix: 최초로그인시 유저상태 2로 설정
  src/auth.config.ts
Labels: :bug: FIX

#232 위치 챌린지 예외 처리 개선
  src/services/challenge.location.services.ts
Labels: :bug: FIX

#233 인기 태그 조회 기능 수정
  src/repositories/history.repositories.ts
Labels: :recycle: REFACTOR
