Repository Sweepic/sweepic-Server, pull requests merged in 2025-01, with the labels that each got.

#6 Update: issue 템플릿 수정
  .github/ISSUE_TEMPLATE/기능-구현.md
  .github/ISSUE_TEMPLATE/버그-해결.md
  .github/ISSUE_TEMPLATE/사용자-정의.md
Labels: :memo: DOCS

#10 [SWEP-12] 초기 설정 및 Readme 파일 구성
  .gitignore
  @types/environment.d.ts
  @types/express.d.ts
  README.md
  package.json
  prisma/migrations/20250102152843_sweepic/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  scripts/build.ts
  src/app.ts
  src/db.config.ts
  tsconfig.json
  vscode/settings.json
  yarn.lock
Labels: 📎 CHORE, :memo: DOCS

#12 feature: CI/CD 파이프라인 구축
  .github/workflows/deploy-main.yml
  .github/workflows/test.yml
  @types/environment.d.ts
  package.json
  prisma/migrations/20250105182531_sweepic_migration_test/migration.sql
  prisma/schema.prisma
  src/db.config.ts
Labels: :sparkles: FEAT

#13 [SWEP-22] CI/CD 파이프라인 구축
  .github/workflows/deploy-main.yml
  .github/workflows/test.yml
  @types/environment.d.ts
  README.md
  package.json
  prisma/migrations/20250105182531_sweepic_migration_test/migration.sql
  prisma/schema.prisma
  src/db.config.ts
Labels: :sparkles: FEAT

#15 [SWEP-28] GTS 적용 및 코드 컨벤션 문서 정리
  .editorconfig
  .prettierrc.cjs
  .vscode/settings.json
  README.md
  docs/CODE_CONVENTION.md
  eslint.config.js
  package.json
  scripts/build.ts
  src/app.ts
  src/db.config.ts
  tsconfig.json
  vscode/settings.json
  yarn.lock
Labels: 📎 CHORE, :memo: DOCS

#17 [SWEP-28] yarn.cmd 수정
  package.json
Labels: :bug: FIX

#19 [SWEP-28] lint, fix 시 parser 에러 해결
  .vscode/settings.json
  eslint.config.js
  package.json
  tsconfig.json
  yarn.lock
Labels: :bug: FIX

#20 fix: 컴파일 결과물 미생성
  tsconfig.json
Labels: :bug: FIX

#18 [SWEP-28] GTS 적용 및 코드 컨벤션 문서 정리
  .editorconfig
  .prettierrc.cjs
  .vscode/settings.json
  README.md
  docs/CODE_CONVENTION.md
  eslint.config.js
  package.json
  scripts/build.ts
  src/app.ts
  src/db.config.ts
  tsconfig.json
  vscode/settings.json
  yarn.lock
Labels: 📎 CHORE, :memo: DOCS

#22 chore: Swagger 연결
  eslint.config.js
  package.json
  src/app.ts
  yarn.lock
Labels: 📎 CHORE

#24 [SWEP-35] Swagger host 변경
  src/app.ts
Labels: :bug: FIX

#27 fix: 빌드 시 스웨거 문서 미복사 문제 해결
  .github/workflows/deploy-main.yml
  package.json
  scripts/build.ts
  src/app.ts
  tsconfig.json
  yarn.lock
Labels: :bug: FIX

#28 [SWEP-35] 빌드 시 스웨거 문서 미복사 문제 해결 (#27)
  .github/workflows/deploy-main.yml
  package.json
  scripts/build.ts
  src/app.ts
  yarn.lock
Labels: :bug: FIX

#32 feature: AWS S3 클라이언트 설정 및 파일 관리 함수 구현
  @types/environment.d.ts
  @types/express.d.ts
  package.json
  scripts/build.ts
  src/app.ts
  src/db.config.ts
  src/models/user.model.ts
  src/s3/awsS3Client.ts
  src/s3/image.deleter.ts
  src/s3/image.mover.ts
  src/s3/image.uploader.ts
  yarn.lock
Labels: :sparkles: FEAT

#35 feature: AWS S3 클라이언트 설정 및 파일 관리 함수 구현
  @types/environment.d.ts
  @types/express.d.ts
  package.json
  src/models/user.model.ts
  src/s3/awsS3Client.ts
  src/s3/image.deleter.ts
  src/s3/image.mover.ts
  src/s3/image.uploader.ts
  yarn.lock
Labels: :sparkles: FEAT

#36 [SWEP-43] AWS S3 파일 관리 함수 구현
  @types/environment.d.ts
  @types/express.d.ts
  package.json
  src/models/user.model.ts
  src/s3/awsS3Client.ts
  src/s3/image.deleter.ts
  src/s3/image.mover.ts
  src/s3/image.uploader.ts
  yarn.lock
Labels: :sparkles: FEAT

#39 chore: prisma 스키마 생성 및 RDS 마이그레이션 적용
  .vscode/settings.json
  prisma/migrations/20250115104835_test/migration.sql
  prisma/migrations/20250115115450_tag_content_limit_10/migration.sql
  prisma/migrations/20250115144526_add_challenge/migration.sql
  prisma/schema.prisma
  src/models/user.model.ts
Labels: 📎 CHORE

#40 [SWEP-36] RDS 마이그레이션 적용 및 스키마 작성
  .vscode/settings.json
  prisma/migrations/20250115104835_test/migration.sql
  prisma/migrations/20250115115450_tag_content_limit_10/migration.sql
  prisma/migrations/20250115144526_add_challenge/migration.sql
  prisma/schema.prisma
  src/models/user.model.ts
Labels: 📎 CHORE

#45 feature: 메모장 POST API 구현
  @types/express.d.ts
  package.json
  src/app.ts
  src/controllers/memo-folder.controller.ts
  src/controllers/memo-image.controller.ts
  src/dtos/memo-folder.dto.ts
  src/dtos/memo-image.dto.ts
  src/models/memo-folder.model.ts
  src/models/memo-image.model.ts
  src/models/user.model.ts
  src/repositories/memo-folder.repository.ts
  src/repositories/memo-image.repository.ts
  src/routers/memo.router.ts
  src/s3/get-presigned-url.ts
  src/s3/image.deleter.ts
  src/s3/image.mover.ts
  src/s3/image.uploader.ts
  src/services/memo-folder.service.ts
  src/services/memo-image.service.ts
  yarn.lock
Labels: :sparkles: FEAT

#47 refactor: req.file MulterS3File 타입 지정, 구조분해 및 Shorthand Property 적용
  src/app.ts
  src/controllers/memo-folder.controller.ts
  src/dtos/memo-folder.dto.ts
  src/dtos/memo-image.dto.ts
  src/models/memo-folder.model.ts
  src/s3/get-presigned-url.ts
Labels: :recycle: REFACTOR

#50 chore: express-async-handler 삭제
  package.json
  src/routers/memo.router.ts
  yarn.lock
Labels: 📎 CHORE

#46 [SWEP-42] 메모장 POST API 구현
  @types/express.d.ts
  package.json
  src/app.ts
  src/controllers/memo-folder.controller.ts
  src/controllers/memo-image.controller.ts
  src/dtos/memo-folder.dto.ts
  src/dtos/memo-image.dto.ts
  src/models/memo-folder.model.ts
  src/models/memo-image.model.ts
  src/models/user.model.ts
  src/repositories/memo-folder.repository.ts
  src/repositories/memo-image.repository.ts
  src/routers/memo.router.ts
  src/s3/get-presigned-url.ts
  src/s3/image.deleter.ts
  src/s3/image.mover.ts
  src/s3/image.uploader.ts
  src/services/memo-folder.service.ts
  src/services/memo-image.service.ts
  yarn.lock
Labels: :sparkles: FEAT

#53 [SWEP-50] 메모장 조회 API 구현
  src/controllers/memo-folder.controller.ts
  src/controllers/memo-image.controller.ts
  src/dtos/memo-folder.dto.ts
  src/models/memo-folder.model.ts
  src/repositories/memo-folder.repository.ts
  src/routers/memo.router.ts
  src/services/memo-folder.service.ts
Labels: :sparkles: FEAT

#54 refactor: 메모 리스트 조회 응답에 사진 장수 추가
  src/controllers/memo-folder.controller.ts
  src/dtos/memo-folder.dto.ts
  src/models/memo-folder.model.ts
  src/repositories/memo-folder.repository.ts
Labels: :recycle: REFACTOR

#56 fix: Session 테이블 수정 및 마이그레이션 파일 추가
  prisma/migrations/20250121060755_session_table_update/migration.sql
  prisma/schema.prisma
Labels: :bug: FIX

#57 [SWEP-51] Session 테이블 수정 및 마이그레이션 추가
  prisma/migrations/20250121060755_session_table_update/migration.sql
  prisma/schema.prisma
Labels: :bug: FIX

#60 refactor: return type 지정
  src/controllers/memo-folder.controller.ts
  src/controllers/memo-image.controller.ts
  src/dtos/memo-folder.dto.ts
  src/dtos/memo-image.dto.ts
  src/models/memo-folder.model.ts
  src/models/memo-image.model.ts
  src/repositories/memo-folder.repository.ts
  src/repositories/memo-image.repository.ts
  src/s3/get-presigned-url.ts
  src/s3/image.deleter.ts
  src/s3/image.mover.ts
  src/services/memo-folder.service.ts
  src/services/memo-image.service.ts
Labels: :recycle: REFACTOR

#59 [SWEP-50] 메모장 조회 API 구현
  src/controllers/memo-folder.controller.ts
  src/controllers/memo-image.controller.ts
  src/dtos/memo-folder.dto.ts
  src/dtos/memo-image.dto.ts
  src/models/memo-folder.model.ts
  src/models/memo-image.model.ts
  src/repositories/memo-folder.repository.ts
  src/repositories/memo-image.repository.ts
  src/routers/memo.router.ts
  src/s3/get-presigned-url.ts
  src/s3/image.deleter.ts
  src/s3/image.mover.ts
  src/services/memo-folder.service.ts
  src/services/memo-image.service.ts
Labels: :sparkles: FEAT

#62 [SWEP-40] 소셜 로그인 구현
  package.json
  src/app.ts
  src/auth.config.ts
  src/models/auth.entities.ts
  src/models/user.model.ts
  src/routers/auth.routers.ts
  yarn.lock
Labels: :sparkles: FEAT

#72 feature: 태그 생성 및 수정 api
  .gitignore
  .idea/.gitignore
  .idea/dataSources.xml
  .idea/modules.xml
  .idea/sweepic-Server.iml
  .idea/vcs.xml
  src/app.ts
  src/controllers/memo-image.controller.ts
  src/controllers/tag.controller.ts
  src/dtos/tag.dto.ts
  src/models/tag.model.ts
  src/repositories/tag.repositories.ts
  src/routers/tag.router.ts
  src/services/tag.service.ts
  tsconfig.json
Labels: :sparkles: FEAT

#63 [SWEP-48] OCR API POST와 PATCH 구현
  .gitignore
  package.json
  src/app.ts
  src/controllers/memo-createFolderOCR.Controller.ts
  src/controllers/memo-updateFolderOCR.Controller.ts
  src/models/memo-OCR.model.ts
  src/models/memo-folder.model.ts
  src/models/memo-image.model.ts
  src/repositories/memo-OCR.repositoy.ts
  src/routers/memo.router.ts
  src/services/memo-ocrService.ts
  yarn.lock
Labels: :sparkles: FEAT

#79 feature: 이미지 비활성화 및 활성화 / 휴지통 비우기(비활성화 이미지 삭제)
  .gitignore
  .idea/.gitignore
  .idea/dataSources.xml
  .idea/modules.xml
  .idea/sweepic-Server.iml
  .idea/vcs.xml
  src/app.ts
  src/controllers/memo-image.controller.ts
  src/controllers/tag.controller.ts
  src/controllers/trust.controller.ts
  src/dtos/image.dto.ts
  src/dtos/tag.dto.ts
  src/models/image.model.ts
  src/models/tag.model.ts
  src/repositories/tag.repositories.ts
  src/repositories/trust.repositories.ts
  src/routers/tag.router.ts
  src/routers/trust.router.ts
  src/services/tag.service.ts
  src/services/trust.service.ts
  tsconfig.json
Labels: :sparkles: FEAT

#84 feature: 날짜별 태그모아보기, 태그검색, tsoa 설정, 스웨거 정적파일 생성
  config/tsoa.json
  src/app.ts
  src/controllers/image.controller.ts
  src/controllers/tsoaTag.controller.ts
  src/dtos/image.dto.ts
  src/dtos/tsoaTag.dto.ts
  src/models/tsoaTag.model.ts
  src/repositories/image.repository.ts
  src/repositories/tsoaTag.repository.ts
  src/routers/tsoaRoutes.ts
  src/services/image.service.ts
  src/services/tsoaTag.service.ts
  swagger/swagger.json
  tsconfig.json
Labels: 📎 CHORE, :sparkles: FEAT

#78 [SWEP-59] 소셜 로그인 오류 해결
  src/app.ts
  src/routers/auth.routers.ts
Labels: :bug: FIX

#92 feature: 메모장 수정 및 삭제 API 구현
  src/controllers/memo-createFolderOCR.Controller.ts
  src/controllers/memo-folder.controller.ts
  src/controllers/memo-image.controller.ts
  src/dtos/memo-folder.dto.ts
  src/dtos/memo-image.dto.ts
  src/models/memo-folder.model.ts
  src/models/memo-image.model.ts
  src/repositories/memo-folder.repository.ts
  src/repositories/memo-image.repository.ts
  src/routers/memo.router.ts
  src/s3/image.mover.ts
  src/s3/image.uploader.ts
  src/services/memo-folder.service.ts
  src/services/memo-image.service.ts
Labels: :sparkles: FEAT

#95 [SWEP-67] 1차 배포 에러 해결
  .github/workflows/deploy-main.yml
  package.json
Labels: :bug: FIX

#98 1차 배포 - 테스트 3차 시도
  .github/workflows/deploy-main.yml
Labels: :bug: FIX

#100 [SWEP-67] 스웨거 정적파일로 배포
  .github/workflows/deploy-main.yml
  src/app.ts
  swagger/openapi.json
  swagger/swagger.ts
  tsconfig.json
Labels: :bug: FIX

#101 [SWEP-67] merge develop to main
  .github/workflows/deploy-main.yml
  src/app.ts
  swagger/openapi.json
  swagger/swagger.ts
  tsconfig.json
Labels: :memo: DOCS, :bug: FIX

#83 [SWEP-52] 날짜 기반 챌린지
  src/controllers/challenge.controllers.ts
  src/controllers/challenge.location.controllers.ts
  src/controllers/challenge.weekly.controllers.ts
  src/dtos/challenge.dtos.ts
  src/models/challenge.entities.ts
  src/repositories/challenge.repositories.ts
  src/repositories/weekly.repositories.ts
  src/routers/challenge.router.ts
  src/services/challenge.location.services.ts
  src/services/challenge.services.ts
  src/services/challenge.weekly.services.ts
Labels: :sparkles: FEAT

#104 [SWEP-61] 응답 및 에러코드 통합
  @types/express.d.ts
  src/app.ts
  src/controllers/memo-createFolderOCR.Controller.ts
  src/controllers/memo-folder.controller.ts
  src/controllers/memo-image.controller.ts
  src/controllers/memo-updateFolderOCR.Controller.ts
  src/errors.ts
  src/services/challenge.services.ts
  src/services/memo-folder.service.ts
  src/services/memo-image.service.ts
  src/services/memo-ocrService.ts
Labels: :recycle: REFACTOR

#114 날짜기반 태그검색, 태그기반 이미지검색 응답 통일, 스웨거 수정, 깃 워크플로우 수정
  .github/workflows/deploy-main.yml
  @types/express.d.ts
  config/tsoa.json
  package.json
  scripts/build.ts
  src/app.ts
  src/controllers/challenge.controllers.ts
  src/controllers/challenge.location.controllers.ts
  src/controllers/challenge.weekly.controllers.ts
  src/controllers/memo-createFolderOCR.Controller.ts
  src/controllers/memo-folder.controller.ts
  src/controllers/memo-image.controller.ts
  src/controllers/memo-updateFolderOCR.Controller.ts
  src/controllers/tsoaImage.controller.ts
  src/controllers/tsoaTag.controller.ts
  src/dtos/challenge.dtos.ts
  src/dtos/tsoaImage.dto.ts
  src/dtos/tsoaTag.dto.ts
  src/errors.ts
  src/models/challenge.entities.ts
  src/models/tsoaResponse.ts
  src/repositories/challenge.repositories.ts
  src/repositories/image.repository.ts
  src/repositories/tsoaImage.repository.ts
  src/repositories/tsoaTag.repository.ts
  src/repositories/weekly.repositories.ts
  src/routers/auth.routers.ts
  src/routers/challenge.router.ts
  src/routers/tsoaRoutes.ts
  src/services/challenge.location.services.ts
  src/services/challenge.services.ts
  src/services/challenge.weekly.services.ts
  src/services/memo-folder.service.ts
  src/services/memo-image.service.ts
  src/services/memo-ocrService.ts
  src/services/tsoaImage.service.ts
  src/services/tsoaTag.service.ts
  swagger/openapi.json
  swagger/swagger.json
  swagger/swagger.ts
  tsconfig.json
Labels: :recycle: REFACTOR, :memo: DOCS, :sparkles: FEAT

#85 [SWEP-60] 날짜별 태그 검색 API, 태그로 이미지 검색 API 기능 구현과 여러 설정
  .github/workflows/deploy-main.yml
  config/tsoa.json
  package.json
  scripts/build.ts
  src/app.ts
  src/controllers/tsoaImage.controller.ts
  src/controllers/tsoaTag.controller.ts
  src/dtos/tsoaImage.dto.ts
  src/dtos/tsoaTag.dto.ts
  src/errors.ts
  src/models/tsoaResponse.ts
  src/models/tsoaTag.model.ts
  src/repositories/tsoaImage.repository.ts
  src/repositories/tsoaTag.repository.ts
  src/routers/tsoaRoutes.ts
  src/services/memo-ocrService.ts
  src/services/tsoaImage.service.ts
  src/services/tsoaTag.service.ts
  swagger/openapi.json
  swagger/swagger.json
  tsconfig.json
Labels: :memo: DOCS, :sparkles: FEAT

#119 refactor: 에러메시지 통합
  .github/workflows/deploy-main.yml
  @types/express.d.ts
  package.json
  src/app.ts
  src/controllers/challenge.controllers.ts
  src/controllers/challenge.location.controllers.ts
  src/controllers/challenge.weekly.controllers.ts
  src/controllers/memo-createFolderOCR.Controller.ts
  src/controllers/memo-folder.controller.ts
  src/controllers/memo-image.controller.ts
  src/controllers/memo-updateFolderOCR.Controller.ts
  src/dtos/challenge.dtos.ts
  src/errors.ts
  src/models/challenge.entities.ts
  src/repositories/challenge.repositories.ts
  src/repositories/memo-folder.repository.ts
  src/repositories/memo-image.repository.ts
  src/repositories/weekly.repositories.ts
  src/routers/challenge.router.ts
  src/s3/image.uploader.ts
  src/services/challenge.location.services.ts
  src/services/challenge.services.ts
  src/services/challenge.weekly.services.ts
  src/services/memo-folder.service.ts
  src/services/memo-image.service.ts
  src/services/memo-ocrService.ts
  swagger/openapi.json
  swagger/swagger.ts
  tsconfig.json
Labels: :recycle: REFACTOR

#117 [SWEP-72] 메모장 에러 핸들링 수정 / AI .env값 사용하도록 로직 변경 / 이미지 라벨링 api 구현(AI)
  @types/express.d.ts
  src/controllers/memo-createFolderOCR.Controller.ts
  src/controllers/memo-folder.controller.ts
  src/controllers/memo-image.controller.ts
  src/controllers/memo-updateFolderOCR.Controller.ts
  src/controllers/tags-ai.controller.ts
  src/errors.ts
  src/models/user.model.ts
  src/services/memo-ocrService.ts
  src/services/tags-ai.service.ts
Labels: :recycle: REFACTOR

#93 [SWEP-66] 메모장 수정 및 삭제 API 구현 (#92)
  package.json
  src/app.ts
  src/controllers/memo-createFolderOCR.Controller.ts
  src/controllers/memo-folder.controller.ts
  src/controllers/memo-image.controller.ts
  src/controllers/memo-updateFolderOCR.Controller.ts
  src/dtos/memo-folder.dto.ts
  src/dtos/memo-image.dto.ts
  src/errors.ts
  src/models/memo-folder.model.ts
  src/models/memo-image.model.ts
  src/repositories/memo-folder.repository.ts
  src/repositories/memo-image.repository.ts
  src/routers/memo.router.ts
  src/s3/image.mover.ts
  src/s3/image.uploader.ts
  src/services/memo-folder.service.ts
  src/services/memo-image.service.ts
  src/services/memo-ocrService.ts
  tsconfig.json
Labels: :sparkles: FEAT

#108 [SWEP-63] 인증 미들웨어 구현 및 온보딩 API
  @types/express.d.ts
  package.json
  src/app.ts
  src/auth.config.ts
  src/controllers/user.controller.ts
  src/errors.ts
  src/routers/auth.routers.ts
  src/routers/user.router.ts
  src/services/user.service.ts
  yarn.lock
Labels: :sparkles: FEAT

#112 [SWEP-68] 챌린지 수락, 완료, 조회, 에러 핸들링
  @types/express.d.ts
  package.json
  src/controllers/challenge.controllers.ts
  src/controllers/challenge.location.controllers.ts
  src/controllers/challenge.weekly.controllers.ts
  src/controllers/memo-createFolderOCR.Controller.ts
  src/dtos/challenge.dtos.ts
  src/errors.ts
  src/models/challenge.entities.ts
  src/repositories/challenge.repositories.ts
  src/routers/challenge.router.ts
  src/services/challenge.location.services.ts
  src/services/challenge.services.ts
  src/services/challenge.weekly.services.ts
  swagger/openapi.json
  swagger/swagger.ts
  yarn.lock
Labels: :sparkles: FEAT
